# Generated by Django 4.1.7 on 2023-03-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(default='defaultprouct.jpeg', upload_to='product_pics')),
                ('price', models.FloatField(default=1.0)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('S', 'Seeds'), ('Ft', 'Fertilizers')], max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller')),
            ],
        ),
    ]
