# Generated by Django 4.1.7 on 2023-03-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='is_superuser',
        ),
    ]
