# Generated by Django 4.1.7 on 2023-03-04 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyer_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
