# Generated by Django 4.1.7 on 2023-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_buyer_date_joined_buyer_is_active_buyer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
